version: "3.8"

services:
  smart_task_fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_task_fe
    restart: unless-stopped
    ports:
      - "3001:80" # Port 3001 di VPS, Nginx VPS Anda akan melakukan reverse proxy ke http://localhost:3001
    networks:
      - costume_shared_net

networks:
  costume_shared_net:
    external: true
    name: shared-network # Menghubungkan ke network existing di VPS
